version: "3"

services:
  redis:
    image: redis:7-alpine
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: secret
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    restart: always
    ports:
      - "8090:8080"
    environment:
      SWAGGER_JSON: /api/v1/swagger.json
      BASE_PATH: /api/v1
    volumes:
      - ./docs:/api/v1

volumes:
  redis-insight:
