// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/transfer": {
            "post": {
                "description": "Process a money transfer between accounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Transfer money between accounts",
                "operationId": "transfer",
                "parameters": [
                    {
                        "description": "Transfer request",
                        "name": "200",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/microBatchService.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Transfer processed successfully",
                        "schema": {
                            "$ref": "#/definitions/microBatchService.TransferResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "microBatchService.Transfer": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "fromAccount": {
                    "type": "string"
                },
                "toAccount": {
                    "type": "string"
                }
            }
        },
        "microBatchService.TransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "from_account": {
                    "type": "string"
                },
                "to_account": {
                    "type": "string"
                }
            }
        },
        "microBatchService.TransferResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "transfer": {
                    "$ref": "#/definitions/microBatchService.Transfer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
